const vscode = require('vscode');
const backendClient = require('./backendClient');
const diffService = require('./diffService');
const languageDetector = require('../utils/languageDetector');
const privacyService = require('./privacyService');
const logger = require('../utils/logger');

class FixService {
  async fixIssue(targetIssue, fileUri) {
    let issue = targetIssue;
    let docUri = fileUri;

    // If invoked from Command Palette without args, pick from current editor diagnostics
    if (!issue || !docUri) {
      const editor = vscode.window.activeTextEditor;
      if (!editor) {
        vscode.window.showInformationMessage('DebugMind: Please open a file with detected issues.');
        return;
      }
      docUri = editor.document.uri;

      // Find issue at cursor or first issue in file
      const cursorLine = editor.selection.active.line + 1;
      const issues = require('../diagnostics/diagnosticManager').getIssuesForFile(docUri);

      if (issues.length === 0) {
        vscode.window.showInformationMessage('DebugMind: No detected issues to fix in current file. Run "Analyze Current File" first.');
        return;
      }

      issue = issues.find(i => i.startLine === cursorLine) || issues[0];
    }

    const approved = await privacyService.confirmSendSource('generate an AI fix for the issue');
    if (!approved) return;

    await vscode.window.withProgress({
      location: vscode.ProgressLocation.Notification,
      title: `DebugMind: Generating AI fix for ${issue.title || issue.id}...`,
      cancellable: false
    }, async () => {
      try {
        const document = await vscode.workspace.openTextDocument(docUri);
        const language = languageDetector.detect(document);
        const fullCode = document.getText();

        const payload = {
          issueId: issue.id,
          title: issue.title,
          category: issue.category,
          explanation: issue.explanation,
          startLine: issue.startLine,
          endLine: issue.endLine,
          language,
          fileName: document.fileName.split(/[/\\]/).pop(),
          code: fullCode
        };

        const fixResponse = await backendClient.generateFix(payload);

        if (!fixResponse.edits || fixResponse.edits.length === 0) {
          vscode.window.showWarningMessage(`DebugMind: No automated edits could be generated for ${issue.id}.`);
          return;
        }

        // Validate edits against file bounds
        const lineCount = document.lineCount;
        for (const edit of fixResponse.edits) {
          if (edit.startLine < 1 || edit.startLine > lineCount + 1) {
            throw new Error(`Invalid line range generated by AI: line ${edit.startLine} exceeds document lines.`);
          }
        }

        // Display VS Code native diff for user review
        await diffService.showDiff(docUri, fixResponse, issue);
      } catch (err) {
        logger.error('Fix generation failed', err);
        vscode.window.showErrorMessage(`DebugMind: ${err.message}`);
      }
    });
  }
}

module.exports = new FixService();
